### ISSUE TITLE
multiple instance spawned

### ISSUE THREAD

**Issue by Xeno-u** [Tnze/tauri-plugin-pty#2]
Hey this is a great plugin and thank you for it.
Unfortunately I found a problem while developing.  And its that when spawning more than 3 terminal instances. (for multi tap or webview support), the whole app stops working funny and the other 3 terminals don't work. I dont know what the problem is. I checked the source code but i couldnt find the issue as I am not a fulltime rust developer.
I am using windows 10 for developing my tauri app.
my versions are:
rustc = "1.76"
tauri = "1.5.6"
tauri-plugin-pty = "0.0.8"
I do not think there is any need to provide reproducing steps.
I am awaiting for your response and thanks you once again.

**Comment by Tnze** [comment]
I'm afraid that I can't offer more help, sorry about that. Because this plugin is just gluing things up and I don't know details either.

**Comment by Xeno-u** [comment]
Thanks for your early response.
I noticed that you used the portable_pty as the pty service in your plugin and when I use portable_pty, I can spawn as many instances of terminals as I want but the problem I have with the portable_pty is the writer which makes crooked text to show up in terminal.
By this conclusion I assume the problem we have here is from the plugin developed thanks to you. Please reconsider and try to reproduce if you will.
tnx again

**Comment by Tnze** [comment]
Can you explain how is your application stopped working when spawn the 4th instance? 
Is the entire web-view frozen or just the events and callbacks didn't trigger any more?

**Comment by Xeno-u** [comment]
ok here goes:

1. My custom made titlebar doesn't drag and close or maximize and... anymore.
2. All the terminals (instances) spawned do not read or write anymore. (they froze)
In general everything that is being handled by the rust side (backend) of the application such and #[tauri::commands] and plugins is down and only the javascript side is alive(such and states and effects which are frontend parts.)

**Comment by Tnze** [comment]
So it sounds like the rust side is frozen, the frontend is still working. Is there deadlock?

**Comment by Xeno-u** [comment]
Ok I found sth I think it can help you. The problem doesnt exist on the 0.0.6 version. But on 0.0.8 version there is this error now: (as a matter of fact there are 20 of them)

```
error[E0432]: unresolved import 'std::sync::Ordering'       
 --> C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-plugin-pty-0.0.8\src\lib.rs:6
:31
  |
6 |     sync::{atomic::AtomicU32, Ordering},
  |                               ^^^^^^^^ no 'Ordering' in 'sync'
  |
  = help: consider importing one of these items instead:
          core::cmp::Ordering
          core::sync::atomic::Ordering
          std::cmp::Ordering
          std::sync::atomic::Ordering

error[E0277]: 'Rc<Session>' cannot be sent between threads safely
   --> C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-plugin-pty-0.0.8\src\lib.rs
:59:12
    |
59  |     state: tauri::State<'_, PluginState>,
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 'Rc<Session>' cannot be sent between threads safely
    |
    = help: the trait 'Send' is not implemented for 'Rc<Session>'
    = note: required for 'NodeRef<Owned, u32, Rc<Session>, LeafOrInternal>' to implement 'Send'
    = note: the full type name has been written to 'C:\Users\ME\Desktop\teeest\src-tauri\target\debug\dep
s\tauri_plugin_pty-eb2fc8c88e6e3209.long-type-15140463929149502130.txt'
note: required because it appears within the type 'Option<NodeRef<Owned, u32, Rc<Session>, LeafOrInternal>>'
   --> C:\Users\ME\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\core\src
\option.rs:570:10
    |
570 | pub enum Option<T> {
    |          ^^^^^^
note: required because it appears within the type 'BTreeMap<u32, Rc<Session>>'
   --> C:\Users\ME\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\alloc\sr
c\collections\btree\map.rs:172:12
    |
172 | pub struct BTreeMap<
    |            ^^^^^^^^
    = note: required for 'tauri::async_runtime::RwLock<BTreeMap<u32, Rc<Session>>>' to implement 'Send'     
note: required because it appears within the type 'PluginState'
   --> C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-plugin-pty-0.0.8\src\lib.rs
:17:8
    |
17  | struct PluginState {
    |        ^^^^^^^^^^^
note: required by a bound in 'State'
   --> C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-1.6.1\src\state.rs:14:25   
    |
14  | pub struct State<'r, T: Send + Sync + 'static>(&'r T);
    |                         ^^^^ required by this bound in 'State'

error[E0277]: 'Rc<Session>' cannot be shared between threads safely
   --> C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-plugin-pty-0.0.8\src\lib.rs
:59:12
    |
59  |     state: tauri::State<'_, PluginState>,
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 'Rc<Session>' cannot be shared between threads safely        
    |
    = help: the trait 'Sync' is not implemented for 'Rc<Session>'
    = note: required for 'NodeRef<Owned, u32, Rc<Session>, LeafOrInternal>' to implement 'Sync'
    = note: the full type name has been written to 'C:\Users\ME\Desktop\teeest\src-tauri\target\debug\dep
s\tauri_plugin_pty-eb2fc8c88e6e3209.long-type-15140463929149502130.txt'
note: required because it appears within the type 'Option<NodeRef<Owned, u32, Rc<Session>, LeafOrInternal>>'
   --> C:\Users\ME\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\core\src
\option.rs:570:10
    |
570 | pub enum Option<T> {
    |          ^^^^^^
note: required because it appears within the type 'BTreeMap<u32, Rc<Session>>'
   --> C:\Users\ME\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\alloc\sr
c\collections\btree\map.rs:172:12
    |
172 | pub struct BTreeMap<
    |            ^^^^^^^^
    = note: required for 'tauri::async_runtime::RwLock<BTreeMap<u32, Rc<Session>>>' to implement 'Sync'     
note: required because it appears within the type 'PluginState'
   --> C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-plugin-pty-0.0.8\src\lib.rs
:17:8
    |
17  | struct PluginState {
    |        ^^^^^^^^^^^
note: required by a bound in 'State'
   --> C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-1.6.1\src\state.rs:14:32   
    |
14  | pub struct State<'r, T: Send + Sync + 'static>(&'r T);
    |                                ^^^^ required by this bound in 'State'

error[E0277]: 'Rc<Session>' cannot be sent between threads safely
   --> C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-plugin-pty-0.0.8\src\lib.rs
:108:12
    |
108 |     state: tauri::State<'_, PluginState>,
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 'Rc<Session>' cannot be sent between threads safely
    |
    = help: the trait 'Send' is not implemented for 'Rc<Session>'
    = note: required for 'NodeRef<Owned, u32, Rc<Session>, LeafOrInternal>' to implement 'Send'
    = note: the full type name has been written to 'C:\Users\ME\Desktop\teeest\src-tauri\target\debug\dep
s\tauri_plugin_pty-eb2fc8c88e6e3209.long-type-15140463929149502130.txt'
note: required because it appears within the type 'Option<NodeRef<Owned, u32, Rc<Session>, LeafOrInternal>>'
   --> C:\Users\ME\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\core\src
\option.rs:570:10
    |
570 | pub enum Option<T> {
    |          ^^^^^^
note: required because it appears within the type 'BTreeMap<u32, Rc<Session>>'
   --> C:\Users\ME\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\alloc\sr
c\collections\btree\map.rs:172:12
    |
172 | pub struct BTreeMap<
    |            ^^^^^^^^
    = note: required for 'tauri::async_runtime::RwLock<BTreeMap<u32, Rc<Session>>>' to implement 'Send'     
note: required because it appears within the type 'PluginState'
   --> C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-plugin-pty-0.0.8\src\lib.rs
:17:8
    |
17  | struct PluginState {
    |        ^^^^^^^^^^^
note: required by a bound in 'State'
   --> C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-1.6.1\src\state.rs:14:25   
    |
14  | pub struct State<'r, T: Send + Sync + 'static>(&'r T);
    |                         ^^^^ required by this bound in 'State'

error[E0277]: 'Rc<Session>' cannot be shared between threads safely
   --> C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-plugin-pty-0.0.8\src\lib.rs
:108:12
    |
108 |     state: tauri::State<'_, PluginState>,
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 'Rc<Session>' cannot be shared between threads safely        
    |
    = help: the trait 'Sync' is not implemented for 'Rc<Session>'
    = note: required for 'NodeRef<Owned, u32, Rc<Session>, LeafOrInternal>' to implement 'Sync'
    = note: the full type name has been written to 'C:\Users\ME\Desktop\teeest\src-tauri\target\debug\dep
s\tauri_plugin_pty-eb2fc8c88e6e3209.long-type-15140463929149502130.txt'
note: required because it appears within the type 'Option<NodeRef<Owned, u32, Rc<Session>, LeafOrInternal>>'
   --> C:\Users\ME\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\core\src
\option.rs:570:10
    |
570 | pub enum Option<T> {
    |          ^^^^^^
note: required because it appears within the type 'BTreeMap<u32, Rc<Session>>'
   --> C:\Users\ME\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\alloc\sr
c\collections\btree\map.rs:172:12
    |
172 | pub struct BTreeMap<
    |            ^^^^^^^^
    = note: required for 'tauri::async_runtime::RwLock<BTreeMap<u32, Rc<Session>>>' to implement 'Sync'     
note: required because it appears within the type 'PluginState'
   --> C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-plugin-pty-0.0.8\src\lib.rs
:17:8
    |
17  | struct PluginState {
    |        ^^^^^^^^^^^
note: required by a bound in 'State'
   --> C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-1.6.1\src\state.rs:14:32   
    |
14  | pub struct State<'r, T: Send + Sync + 'static>(&'r T);
    |                                ^^^^ required by this bound in 'State'

error[E0277]: 'Rc<Session>' cannot be sent between threads safely
   --> C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-plugin-pty-0.0.8\src\lib.rs
:124:39
    |
124 | async fn read(pid: PtyHandler, state: tauri::State<'_, PluginState>) -> Result<String, String> {
    |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 'Rc<Session>' cannot be sent betwe
en threads safely
    |
    = help: the trait 'Send' is not implemented for 'Rc<Session>'
    = note: required for 'NodeRef<Owned, u32, Rc<Session>, LeafOrInternal>' to implement 'Send'
    = note: the full type name has been written to 'C:\Users\ME\Desktop\teeest\src-tauri\target\debug\dep
s\tauri_plugin_pty-eb2fc8c88e6e3209.long-type-15140463929149502130.txt'
note: required because it appears within the type 'Option<NodeRef<Owned, u32, Rc<Session>, LeafOrInternal>>'
   --> C:\Users\ME\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\core\src
\option.rs:570:10
    |
570 | pub enum Option<T> {
    |          ^^^^^^
note: required because it appears within the type 'BTreeMap<u32, Rc<Session>>'
   --> C:\Users\ME\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\alloc\sr
c\collections\btree\map.rs:172:12
    |
172 | pub struct BTreeMap<
    |            ^^^^^^^^
    = note: required for 'tauri::async_runtime::RwLock<BTreeMap<u32, Rc<Session>>>' to implement 'Send'     
note: required because it appears within the type 'PluginState'
   --> C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-plugin-pty-0.0.8\src\lib.rs
:17:8
    |
17  | struct PluginState {
    |        ^^^^^^^^^^^
note: required by a bound in 'State'
   --> C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-1.6.1\src\state.rs:14:25   
    |
14  | pub struct State<'r, T: Send + Sync + 'static>(&'r T);
    |                         ^^^^ required by this bound in 'State'

error[E0277]: 'Rc<Session>' cannot be shared between threads safely
   --> C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-plugin-pty-0.0.8\src\lib.rs
:124:39
    |
124 | async fn read(pid: PtyHandler, state: tauri::State<'_, PluginState>) -> Result<String, String> {      
    |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 'Rc<Session>' cannot be shared bet
ween threads safely
    |
    = help: the trait 'Sync' is not implemented for 'Rc<Session>'
    = note: required for 'NodeRef<Owned, u32, Rc<Session>, LeafOrInternal>' to implement 'Sync'
    = note: the full type name has been written to 'C:\Users\ME\Desktop\teeest\src-tauri\target\debug\dep
s\tauri_plugin_pty-eb2fc8c88e6e3209.long-type-15140463929149502130.txt'
note: required because it appears within the type 'Option<NodeRef<Owned, u32, Rc<Session>, LeafOrInternal>>'
   --> C:\Users\ME\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\core\src
\option.rs:570:10
    |
570 | pub enum Option<T> {
    |          ^^^^^^
note: required because it appears within the type 'BTreeMap<u32, Rc<Session>>'
   --> C:\Users\ME\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\alloc\sr
c\collections\btree\map.rs:172:12
    |
172 | pub struct BTreeMap<
    |            ^^^^^^^^
    = note: required for 'tauri::async_runtime::RwLock<BTreeMap<u32, Rc<Session>>>' to implement 'Sync'     
note: required because it appears within the type 'PluginState'
   --> C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-plugin-pty-0.0.8\src\lib.rs
:17:8
    |
17  | struct PluginState {
    |        ^^^^^^^^^^^
note: required by a bound in 'State'
   --> C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-1.6.1\src\state.rs:14:32   
    |
14  | pub struct State<'r, T: Send + Sync + 'static>(&'r T);
    |                                ^^^^ required by this bound in 'State'

error[E0277]: 'Rc<Session>' cannot be sent between threads safely
   --> C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-plugin-pty-0.0.8\src\lib.rs
:143:12
    |
143 |     state: tauri::State<'_, PluginState>,
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 'Rc<Session>' cannot be sent between threads safely
    |
    = help: the trait 'Send' is not implemented for 'Rc<Session>'
    = note: required for 'NodeRef<Owned, u32, Rc<Session>, LeafOrInternal>' to implement 'Send'
    = note: the full type name has been written to 'C:\Users\ME\Desktop\teeest\src-tauri\target\debug\dep
s\tauri_plugin_pty-eb2fc8c88e6e3209.long-type-15140463929149502130.txt'
note: required because it appears within the type 'Option<NodeRef<Owned, u32, Rc<Session>, LeafOrInternal>>'
   --> C:\Users\ME\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\core\src
\option.rs:570:10
    |
570 | pub enum Option<T> {
    |          ^^^^^^
note: required because it appears within the type 'BTreeMap<u32, Rc<Session>>'
   --> C:\Users\ME\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\alloc\sr
c\collections\btree\map.rs:172:12
    |
172 | pub struct BTreeMap<
    |            ^^^^^^^^
    = note: required for 'tauri::async_runtime::RwLock<BTreeMap<u32, Rc<Session>>>' to implement 'Send'     
note: required because it appears within the type 'PluginState'
   --> C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-plugin-pty-0.0.8\src\lib.rs
:17:8
    |
17  | struct PluginState {
    |        ^^^^^^^^^^^
note: required by a bound in 'State'
   --> C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-1.6.1\src\state.rs:14:25   
    |
14  | pub struct State<'r, T: Send + Sync + 'static>(&'r T);
    |                         ^^^^ required by this bound in 'State'

error[E0277]: 'Rc<Session>' cannot be shared between threads safely
   --> C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-plugin-pty-0.0.8\src\lib.rs
:143:12
    |
143 |     state: tauri::State<'_, PluginState>,
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 'Rc<Session>' cannot be shared between threads safely        
    |
    = help: the trait 'Sync' is not implemented for 'Rc<Session>'
    = note: required for 'NodeRef<Owned, u32, Rc<Session>, LeafOrInternal>' to implement 'Sync'
    = note: the full type name has been written to 'C:\Users\ME\Desktop\teeest\src-tauri\target\debug\dep
s\tauri_plugin_pty-eb2fc8c88e6e3209.long-type-15140463929149502130.txt'
note: required because it appears within the type 'Option<NodeRef<Owned, u32, Rc<Session>, LeafOrInternal>>'
   --> C:\Users\ME\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\core\src
\option.rs:570:10
    |
570 | pub enum Option<T> {
    |          ^^^^^^
note: required because it appears within the type 'BTreeMap<u32, Rc<Session>>'
   --> C:\Users\ME\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\alloc\sr
c\collections\btree\map.rs:172:12
    |
172 | pub struct BTreeMap<
    |            ^^^^^^^^
    = note: required for 'tauri::async_runtime::RwLock<BTreeMap<u32, Rc<Session>>>' to implement 'Sync'     
note: required because it appears within the type 'PluginState'
   --> C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-plugin-pty-0.0.8\src\lib.rs
:17:8
    |
17  | struct PluginState {
    |        ^^^^^^^^^^^
note: required by a bound in 'State'
   --> C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-1.6.1\src\state.rs:14:32   
    |
14  | pub struct State<'r, T: Send + Sync + 'static>(&'r T);
    |                                ^^^^ required by this bound in 'State'

error[E0277]: 'Rc<Session>' cannot be sent between threads safely
   --> C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-plugin-pty-0.0.8\src\lib.rs
:165:39
    |
165 | async fn kill(pid: PtyHandler, state: tauri::State<'_, PluginState>) -> Result<(), String> {
    |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 'Rc<Session>' cannot be sent betwe
en threads safely
    |
    = help: the trait 'Send' is not implemented for 'Rc<Session>'
    = note: required for 'NodeRef<Owned, u32, Rc<Session>, LeafOrInternal>' to implement 'Send'
    = note: the full type name has been written to 'C:\Users\ME\Desktop\teeest\src-tauri\target\debug\dep
s\tauri_plugin_pty-eb2fc8c88e6e3209.long-type-15140463929149502130.txt'
note: required because it appears within the type 'Option<NodeRef<Owned, u32, Rc<Session>, LeafOrInternal>>'
   --> C:\Users\ME\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\core\src
\option.rs:570:10
    |
570 | pub enum Option<T> {
    |          ^^^^^^
note: required because it appears within the type 'BTreeMap<u32, Rc<Session>>'
   --> C:\Users\ME\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\alloc\sr
c\collections\btree\map.rs:172:12
    |
172 | pub struct BTreeMap<
    |            ^^^^^^^^
    = note: required for 'tauri::async_runtime::RwLock<BTreeMap<u32, Rc<Session>>>' to implement 'Send'     
note: required because it appears within the type 'PluginState'
   --> C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-plugin-pty-0.0.8\src\lib.rs
:17:8
    |
17  | struct PluginState {
    |        ^^^^^^^^^^^
note: required by a bound in 'State'
   --> C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-1.6.1\src\state.rs:14:25   
    |
14  | pub struct State<'r, T: Send + Sync + 'static>(&'r T);
    |                         ^^^^ required by this bound in 'State'

error[E0277]: 'Rc<Session>' cannot be shared between threads safely
   --> C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-plugin-pty-0.0.8\src\lib.rs
:165:39
    |
165 | async fn kill(pid: PtyHandler, state: tauri::State<'_, PluginState>) -> Result<(), String> {
    |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 'Rc<Session>' cannot be shared bet
ween threads safely
    |
    = help: the trait 'Sync' is not implemented for 'Rc<Session>'
    = note: required for 'NodeRef<Owned, u32, Rc<Session>, LeafOrInternal>' to implement 'Sync'
    = note: the full type name has been written to 'C:\Users\ME\Desktop\teeest\src-tauri\target\debug\dep
s\tauri_plugin_pty-eb2fc8c88e6e3209.long-type-15140463929149502130.txt'
note: required because it appears within the type 'Option<NodeRef<Owned, u32, Rc<Session>, LeafOrInternal>>'
   --> C:\Users\ME\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\core\src
\option.rs:570:10
    |
570 | pub enum Option<T> {
    |          ^^^^^^
note: required because it appears within the type 'BTreeMap<u32, Rc<Session>>'
   --> C:\Users\ME\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\alloc\sr
c\collections\btree\map.rs:172:12
    |
172 | pub struct BTreeMap<
    |            ^^^^^^^^
    = note: required for 'tauri::async_runtime::RwLock<BTreeMap<u32, Rc<Session>>>' to implement 'Sync'     
note: required because it appears within the type 'PluginState'
   --> C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-plugin-pty-0.0.8\src\lib.rs
:17:8
    |
17  | struct PluginState {
    |        ^^^^^^^^^^^
note: required by a bound in 'State'
   --> C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-1.6.1\src\state.rs:14:32   
    |
14  | pub struct State<'r, T: Send + Sync + 'static>(&'r T);
    |                                ^^^^ required by this bound in 'State'

error[E0277]: 'Rc<Session>' cannot be sent between threads safely
   --> C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-plugin-pty-0.0.8\src\lib.rs
:181:45
    |
181 | async fn exitstatus(pid: PtyHandler, state: tauri::State<'_, PluginState>) -> Result<u32, String> {   
    |                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 'Rc<Session>' cannot be sent
 between threads safely
    |
    = help: the trait 'Send' is not implemented for 'Rc<Session>'
    = note: required for 'NodeRef<Owned, u32, Rc<Session>, LeafOrInternal>' to implement 'Send'
    = note: the full type name has been written to 'C:\Users\ME\Desktop\teeest\src-tauri\target\debug\dep
s\tauri_plugin_pty-eb2fc8c88e6e3209.long-type-15140463929149502130.txt'
note: required because it appears within the type 'Option<NodeRef<Owned, u32, Rc<Session>, LeafOrInternal>>'
   --> C:\Users\ME\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\core\src
\option.rs:570:10
    |
570 | pub enum Option<T> {
    |          ^^^^^^
note: required because it appears within the type 'BTreeMap<u32, Rc<Session>>'
   --> C:\Users\ME\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\alloc\sr
c\collections\btree\map.rs:172:12
    |
172 | pub struct BTreeMap<
    |            ^^^^^^^^
    = note: required for 'tauri::async_runtime::RwLock<BTreeMap<u32, Rc<Session>>>' to implement 'Send'     
note: required because it appears within the type 'PluginState'
   --> C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-plugin-pty-0.0.8\src\lib.rs
:17:8
    |
17  | struct PluginState {
    |        ^^^^^^^^^^^
note: required by a bound in 'State'
   --> C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-1.6.1\src\state.rs:14:25   
    |
14  | pub struct State<'r, T: Send + Sync + 'static>(&'r T);
    |                         ^^^^ required by this bound in 'State'

error[E0277]: 'Rc<Session>' cannot be shared between threads safely
   --> C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-plugin-pty-0.0.8\src\lib.rs
:181:45
    |
181 | async fn exitstatus(pid: PtyHandler, state: tauri::State<'_, PluginState>) -> Result<u32, String> {   
    |                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 'Rc<Session>' cannot be shar
ed between threads safely
    |
    = help: the trait 'Sync' is not implemented for 'Rc<Session>'
    = note: required for 'NodeRef<Owned, u32, Rc<Session>, LeafOrInternal>' to implement 'Sync'
    = note: the full type name has been written to 'C:\Users\ME\Desktop\teeest\src-tauri\target\debug\dep
s\tauri_plugin_pty-eb2fc8c88e6e3209.long-type-15140463929149502130.txt'
note: required because it appears within the type 'Option<NodeRef<Owned, u32, Rc<Session>, LeafOrInternal>>'
   --> C:\Users\ME\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\core\src
\option.rs:570:10
    |
570 | pub enum Option<T> {
    |          ^^^^^^
note: required because it appears within the type 'BTreeMap<u32, Rc<Session>>'
   --> C:\Users\ME\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\alloc\sr
c\collections\btree\map.rs:172:12
    |
172 | pub struct BTreeMap<
    |            ^^^^^^^^
    = note: required for 'tauri::async_runtime::RwLock<BTreeMap<u32, Rc<Session>>>' to implement 'Sync'     
note: required because it appears within the type 'PluginState'
   --> C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-plugin-pty-0.0.8\src\lib.rs
:17:8
    |
17  | struct PluginState {
    |        ^^^^^^^^^^^
note: required by a bound in 'State'
   --> C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-1.6.1\src\state.rs:14:32   
    |
14  | pub struct State<'r, T: Send + Sync + 'static>(&'r T);
    |                                ^^^^ required by this bound in 'State'

error[E0609]: no field 'session_id' on type 'State<'_, PluginState>'
--> C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-plugin-pty-0.0.8\src\lib.rs:
92:25
|
92 |     let handler = state.session_id.fetch_add(1, Ordering::Relaxed);
|                         ^^^^^^^^^^ unknown field

error[E0609]: no field 'sessions' on type 'State<'_, PluginState>'
--> C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-plugin-pty-0.0.8\src\lib.rs
:101:11
|
101 |     state.sessions.write().await.insert(handler, session.clone());
|           ^^^^^^^^ unknown field

error[E0609]: no field 'sessions' on type 'State<'_, PluginState>'
--> C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-plugin-pty-0.0.8\src\lib.rs
:111:10
|
111 |         .sessions
|          ^^^^^^^^ unknown field

error[E0609]: no field 'sessions' on type 'State<'_, PluginState>'
--> C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-plugin-pty-0.0.8\src\lib.rs
:126:10
|
126 |         .sessions
|          ^^^^^^^^ unknown field

error[E0609]: no field 'sessions' on type 'State<'_, PluginState>'
--> C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-plugin-pty-0.0.8\src\lib.rs
:146:10
|
146 |         .sessions
|          ^^^^^^^^ unknown field

error[E0609]: no field 'sessions' on type 'State<'_, PluginState>'
--> C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-plugin-pty-0.0.8\src\lib.rs
:167:10
|
167 |         .sessions
|          ^^^^^^^^ unknown field

error[E0609]: no field 'sessions' on type 'State<'_, PluginState>'
--> C:\Users\ME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-plugin-pty-0.0.8\src\lib.rs
:183:10
|
183 |         .sessions
|          ^^^^^^^^ unknown field


Some errors have detailed explanations: E0277, E0432, E0609.
    For more information about an error, try 'rustc --explain E0277'.
    error: could not compile 'tauri-plugin-pty' (lib) due to 20 previous errors
```
i just posted all the errors just in case you want to read them so dont be mad at me please :))
everything seems to work on 0.0.6 so i now you must be sure that there is something wrong with 0.0.8

**Comment by Xeno-u** [comment]
Ok noticed another thing.
on 0.0.6 the limit is no longer 3 instances but it is 7. Which is awesome but just in case you wanna know. 7 is a big number cuz who the heck needs 7 terminals? what kind of a creepy hacker needs it Right? but still would be great if you solved it.

**Comment by Xeno-u** [comment]
noticed another thing.
even if you close the instances it still will have a problem on the 8th instance that has been spawned.

**Comment by Tnze** [comment]
Strange.. 
Can you provide a reproduction so I can test this plugin on it?

**Comment by Xeno-u** [comment]
[Terminaux-master.zip](https://github.com/Tnze/tauri-plugin-pty/files/14961588/Terminaux-master.zip)

**Comment by Xeno-u** [comment]
What's up? any achievements?

**Comment by Tnze** [comment]
Sorry, I was sick these days. I will check it later.

**Comment by Xeno-u** [comment]
Oh damn. Are you OK? I wish you a good health.
Looking forward to hearing from you :)

**Comment by Xeno-u** [comment]
Hey how have you been? Still Working on the update or not?

**Comment by Tnze** [comment]
Yes, I think the problem is found. But I have no solution yet.

The problem of this plugin is the underlying PTY operations aren't true async operations. They block the working threads of tokio (the async runtime).
And your demo code create `n` PTY sessions when new tab created which `n` equals the number of current tabs (which is your bug), exacerbating the problem.

1 tab -> 2 pty
2 tabs -> 4 pty
3 tabs -> 7 pty
4 tabs -> 11 pty
5 tabs -> 16 pty
...

If you increase the number of tokio underlying working threads, the limitation of pty session increases too.

----

What we can do:

1. Report this issue to upstream PTY implementation repository.
2. FIx the bug. You need only 1 pty for each tab.
3. Increase tokio working thread number

```rust
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]
fn main() {
// add this
    let runtime = tokio::runtime::Builder::new_multi_thread()
        .enable_all()
        .max_blocking_threads(512)
        .worker_threads(128)
        .build()
        .unwrap();
    tauri::async_runtime::set(runtime.handle().clone());
/// end
    tauri::Builder::default()
        .plugin(tauri_plugin_pty::init())
        .on_page_load(move |window, _| {
            let window = window.clone();
        })
        .invoke_handler(tauri::generate_handler![])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```

**Comment by Tnze** [comment]
If my analysis is correct, `Wezterm` will also have the same problem. However, the limit number is even greater.

**Comment by Tnze** [comment]
I was unable to reproduce this issue in `Wezterm`. It will be too laggy after creating lots of tabs.

But I took a look on the `portable-pty` source code. Didn't found any problem. Maybe it's related on Tauri? It has a limitation of blocking async command number?

**Comment by Xeno-u** [comment]
Thank you so much.
The tokio runtime Implementation solved the problem.
